# Generated by Django 2.2 on 2020-03-14 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200314_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('general', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='general', max_length=50, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files', verbose_name='Файл'),
        ),
    ]
